export {ImmutableAuthentication as authentication} from './authentication'
export {ImmutableFetchData as fetchData} from './fetchData'
export {ImmutablePreloadReducer as preload} from './preload'
export {ImmutableModals as modals} from './modals'
export {ImmutableRoutingReducer as routing} from './routing'